CREATE DATABASE LAB_RECOMENDADOR;
USE LAB_RECOMENDADOR;

CREATE TABLE AVALIACAO_SUB_TIPO (
	id_usuario INTEGER,
    id_categoria INTEGER,
    avaliacao INTEGER,
    PRIMARY KEY (id_usuario, id_categoria),
	INDEX (id_usuario),
	INDEX (id_categoria)
);

INSERT INTO AVALIACAO_SUB_TIPO VALUES(1,1,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(1,2,9);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(2,2,8);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(2,3,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(3,1,0);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(3,2,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(3,4,9);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(4,1,2);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(4,3,3);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(4,5,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(5,1,9);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(5,4,7);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(6,3,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(6,5,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(7,1,4);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(7,2,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(7,3,5);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(7,4,8);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(8,1,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(8,2,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(8,3,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(8,4,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(8,5,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(9,1,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(9,3,0);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(9,5,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(10,1,7);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(10,2,9);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(10,3,2);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(11,1,9);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(11,2,0);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(11,3,0);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(11,4,0);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(11,5,0);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(12,1,3);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(12,2,9);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(12,3,8);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(12,5,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(13,1,1);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(13,4,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(14,1,9);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(14,3,3);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(15,1,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(15,3,0);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(15,5,5);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(16,2,8);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(16,4,6);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(16,5,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(17,1,9);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(17,2,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(17,5,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(18,2,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(18,4,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(19,2,9);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(19,3,8);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(20,1,9);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(20,2,3);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(20,3,2);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(20,4,6);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(20,5,9);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(1,6,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(8,6,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(9,6,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(11,6,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(14,6,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(20,6,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(4,7,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(6,7,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(8,7,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(9,7,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(12,7,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(15,7,5);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(16,7,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(17,7,10);
INSERT INTO AVALIACAO_SUB_TIPO VALUES(20,7,9);

SELECT * FROM AVALIACAO_SUB_TIPO;

